import React, { useEffect, useState } from 'react';
import {
  Card,
  Button,
  Table,
  Alert,
  Form,
  Spinner,
  Row,
  Col,
  Modal
} from 'react-bootstrap';
import axios from 'axios';

const API_BASE = 'http://localhost:5000/api';

const Recommendations = () => {
  const [stores, setStores] = useState([]);
  const [recommendations, setRecommendations] = useState([]);
  const [selectedStore, setSelectedStore] = useState('');
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);

  // Edit modal states
  const [editModal, setEditModal] = useState(false);
  const [editRec, setEditRec] = useState(null);
  const [editProducts, setEditProducts] = useState('');

  const token = localStorage.getItem('token');
  const headers = { Authorization: `Bearer ${token}` };

  const fetchStores = async () => {
    try {
      const res = await axios.get(`${API_BASE}/stores`, { headers });
      setStores(Array.isArray(res.data) ? res.data : res.data.data || []);
    } catch (err) {
      setMessage('Failed to load stores.');
    }
  };

  const fetchRecommendations = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API_BASE}/recommendations`, { headers });
      setRecommendations(res.data || []);
    } catch (err) {
      setMessage('Failed to load recommendations.');
    }
    setLoading(false);
  };

  const handleGenerate = async () => {
    if (!selectedStore) return setMessage('Please select a store.');

    setLoading(true);
    try {
      const res = await axios.post(
  `${API_BASE}/recommendations/generate`,
  {
    store: selectedStore,
    products: ['Shampoo', 'Face Wash'], // Replace with your logic if needed
    generatedBy: 'admin'
  },
  { headers }
);

      setMessage('✅ Smart recommendations generated.');
      fetchRecommendations();
    } catch (err) {
      setMessage(err.response?.data?.message || 'Failed to generate.');
    }
    setLoading(false);
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this recommendation?')) return;
    try {
      await axios.delete(`${API_BASE}/recommendations/delete/${id}`, { headers });
      setMessage('Recommendation deleted.');
      fetchRecommendations();
    } catch (err) {
      setMessage('Failed to delete recommendation.');
    }
  };

  const openEditModal = (rec) => {
    setEditRec(rec);
    setEditProducts(rec.products.join(', '));
    setEditModal(true);
  };

  const handleEditSave = async () => {
    try {
      const payload = {
        products: editProducts.split(',').map((p) => p.trim()),
        generatedBy: editRec.generatedBy
      };
      await axios.put(`${API_BASE}/recommendations/update/${editRec._id}`, payload, { headers });
      setMessage('Recommendation updated.');
      setEditModal(false);
      fetchRecommendations();
    } catch (err) {
      setMessage('Failed to update recommendation.');
    }
  };

  useEffect(() => {
    fetchStores();
    fetchRecommendations();
  }, []);

  return (
    <Card className="p-4 shadow-sm">
      <h3 className="mb-4">Smart Recommendations</h3>

      {message && (
        <Alert variant="info" dismissible onClose={() => setMessage('')}>
          {message}
        </Alert>
      )}

      <Form className="mb-3">
        <Row className="align-items-end g-2">
          <Col md={8}>
            <Form.Group>
              <Form.Label>Select Store</Form.Label>
              <Form.Select
                value={selectedStore}
                onChange={(e) => setSelectedStore(e.target.value)}
              >
                <option value="">-- Choose Store --</option>
                {stores.map((store) => (
                  <option key={store._id} value={store._id}>
                    {store.name}
                  </option>
                ))}
              </Form.Select>
            </Form.Group>
          </Col>
          <Col md={4}>
            <Button
              onClick={handleGenerate}
              variant="primary"
              className="w-100"
              disabled={!selectedStore || loading}
            >
              {loading ? 'Generating...' : 'Generate Recommendations'}
            </Button>
          </Col>
        </Row>
      </Form>

      {loading ? (
        <div className="text-center my-3">
          <Spinner animation="border" />
        </div>
      ) : (
        <Table striped bordered hover responsive>
          <thead>
            <tr>
              <th>Store</th>
              <th>Products</th>
              <th>Generated By</th>
              <th>Created At</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {recommendations.map((rec, idx) => {
              const store = stores.find((s) => s._id === (rec.store?._id || rec.store));
              return (
                <tr key={idx}>
                  <td>{store?.name || 'Unknown'}</td>
                  <td>{rec.products.join(', ')}</td>
                  <td>{rec.generatedBy}</td>
                  <td>{new Date(rec.createdAt).toLocaleString()}</td>
                  <td>
                    <Button size="sm" onClick={() => openEditModal(rec)} variant="warning" className="me-2">
                      Edit
                    </Button>
                    <Button size="sm" onClick={() => handleDelete(rec._id)} variant="danger">
                      Delete
                    </Button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </Table>
      )}

      {/* Edit Modal */}
      <Modal show={editModal} onHide={() => setEditModal(false)}>
        <Modal.Header closeButton>
          <Modal.Title>Edit Recommendation</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Form.Group>
            <Form.Label>Products (comma-separated)</Form.Label>
            <Form.Control
              type="text"
              value={editProducts}
              onChange={(e) => setEditProducts(e.target.value)}
            />
          </Form.Group>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={() => setEditModal(false)}>
            Cancel
          </Button>
          <Button variant="success" onClick={handleEditSave}>
            Save Changes
          </Button>
        </Modal.Footer>
      </Modal>
    </Card>
  );
};

export default Recommendations;
